# Enable the feeds that you require by removing the underscore from their names.
# You have to edit the exec line(s) to point to your working directory.
# For Cinematik you have to copy your RSS link to the url field.
# For TorrentLeech you have to copy your RSS link from your edit profile page to the url field.

tasks:
# Cinemageddon
  _cinemageddon:
    disable_urlrewriters: [urlrewrite_redirect]
    rss:
      url: http://cinemageddon.net/rss.xml
      # Force ASCII because the feed is not encoded properly.
      ascii: yes
    regexp:
      from: title
      reject:
        - .+\(XXX\)
        - .+\(OST\)
    accept_all: yes
    manipulate:
      # Create TorrentId field by extracting the id from the URL.
      - TorrentId:
          from: url
          extract: 'http://cinemageddon\.net/details\.php\?id=(\d+).*'
    exec: echo '{"AnnouncementSourceName":"cg","AnnouncementId":"{{TorrentId}}"}' > "/data/announcement/cg-{{TorrentId}}.json"

# Karagarga
  _karagarga:
    disable_urlrewriters: [urlrewrite_redirect]
    rss:
      url: https://karagarga.in/rss.php?passkey=AAAAAAAAAAAAAAAA&user=AAAAAAAAAAAAAAAA
      # Force ASCII just to be sure.
      ascii: yes
    regexp:
      from: title
      reject:
        # Ignore literature.
        - .+\[Audiobooks\]$
        - .+\[Books\]$
        - .+\[Comics\]$
        # Ignore music. (Experimental can't be ignored because it is also a movie genre.)
        - .+\[Blues\]$
        - .+\[Classical\]$
        - .+\[Country\]$
        - .+\[Electronica\]$
        - .+\[Exotica\]$
        - .+\[Folk\]$
        - .+\[Funk\]$
        - .+\[Indie\]$
        - .+\[Jazz\]$
        - .+\[Latin\]$
        - .+\[Live\]$
        - .+\[Metal\]$
        - .+\[Punk & Hardcore\]$
        - .+\[Rap & Hiphop\]$
        - .+\[Reggae\]$
        - .+\[Rock\]$
        - .+\[Soul\]$
        - .+\[Soundtrack\]$
        - .+\[World\]$
    accept_all: yes
    manipulate:
      # Create TorrentId field by extracting the ID from the URL.
      - TorrentId:
          from: url
          extract: 'https?://(?:www\.)?karagarga\.in/details\.php\?id=(\d+)'
    exec: echo '{"AnnouncementSourceName":"kg","AnnouncementId":"{{TorrentId}}"}' > "/data/announcement/kg-{{TorrentId}}.json"
